;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	mouse-set-region
	org-ctrl-c-ret
	save-buffers-kill-terminal
	scroll-bar-toolkit-scroll
	))
