# ~/.config/i3/i3status.conf
# i3status configuration file
# see "man i3status" for documentation.

general {
    colors = true
    interval = 5
    markup = "pango"
    color_good = "#b8bb26"
    color_bad = "#fb4934"
    color_degraded = "#fabd2f"
}

order += "wireless _first_"
order += "ethernet _first_"
order += "cpu_usage"
order += "cpu_temperature 0"
order += "read_file gpu_usage"
order += "memory"
order += "disk /"
order += "disk /media/nils/storage"
order += "battery all"
order += "volume master"
order += "tztime local"

# wireless _first_ {
#     format_up = " %quality %essid %ip"
#     format_down = " down"
#     color_good = "#b8bb26"
# }

ethernet _first_ {
    format_up = " %ip (%speed)"
    format_down = " down"
}

cpu_usage {
    format = "CPU: %usage"
    max_threshold = 75
    degraded_threshold = 50
}

# cpu_temperature 0 {
#     format = " %degrees°C"
#     max_threshold = 70
#     path = "/sys/class/thermal/thermal_zone0/temp"
# }

memory {
    format = "RAM: %percentage_used"
    threshold_degraded = "20%"
    threshold_critical = "10%"
}

read_file gpu_usage {
    format = "GPU: %content"
    path = "/tmp/gpu_usage"
    max_characters = 15
    color_good = "#b8bb26"
    color_bad = "#fb4934"
    color_degraded = "#fabd2f"
}

disk "/" {
    format = " root/: %percentage_used (%used/%total)"
    threshold_type = percentage_avail
    low_threshold = 10
}

disk "/media/Storage" {
    format = " Storage/: %percentage_used (%used/%total)"
    threshold_type = percentage_avail
    low_threshold = 10
}

# battery all {
#     format = "%status %percentage %remaining"
#     format_down = " No battery"
#     status_chr = ""
#     status_bat = ""
#     status_unk = ""
#     status_full = ""
#     low_threshold = 15
#     threshold_type = percentage
# }

# volume master {
#     format = " %volume"
#     format_muted = " muted"
#     device = "default"
#     mixer = "Master"
#     mixer_idx = 0
# }

tztime local {
    format = " %Y-%m-%d - %H:%M"
}
